import {
  createBrand,
  createCategory,
  createFullProduct,
  createUnit,
  deleteBrand,
  deleteCategory,
  deleteProduct,
  deleteUnit,
  getBrands,
  getCategories,
  getMainCategories,
  getProductCatalog,
  getProducts,
  getSubCategories,
  getUnitById,
  getUnits,
  normalizeBrand,
  normalizeCategory,
  normalizeProduct,
  normalizeUnit,
  patchProduct,
  updateBrand,
  updateCategory,
  updateProduct,
  updateUnit,
} from '../api/productApi'
import { getSuppliers } from '../api/suppliersApi'
import { getWarehouses } from '../api/warehousesApi'

export const catalogApi = {
  getProducts,
  getProductCatalog,
  getCategories,
  getMainCategories,
  getSubCategories,
  getBrands,
  getUnits,
  getUnitById,
  getSuppliers,
  getWarehouses,
  createProduct: createFullProduct,
  updateProduct,
  patchProduct,
  deleteProduct,
  createCategory,
  updateCategory,
  deleteCategory,
  createBrand,
  updateBrand,
  deleteBrand,
  createUnit,
  updateUnit,
  deleteUnit,
  normalizeCategory,
  normalizeBrand,
  normalizeUnit,
  normalizeProduct,
}
